"""The pack generator's pure half.

Collecting a pack downloads gigabytes and may invoke a compiler, which is the
whole reason ``make_packs.py`` is a script rather than a test. What *can* be
pinned here is everything that decides *which* files it would collect -- the
marker evaluation, the wheel choice and the claim mapping -- and those are the
parts whose being wrong produces a pack that looks complete and installs the
wrong thing.

Two tests read the real ``uv.lock``. They are the ones that would have caught
what this file's own history records: a rule that looked right against
invented filenames and was wrong against half the tree.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

from warlock import packs

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"


@pytest.fixture(scope="module")
def maker():
    sys.path.insert(0, str(SCRIPTS))
    try:
        spec = importlib.util.spec_from_file_location("make_packs", SCRIPTS / "make_packs.py")
        assert spec is not None and spec.loader is not None
        module = importlib.util.module_from_spec(spec)
        sys.modules["make_packs"] = module
        spec.loader.exec_module(module)
        return module
    finally:
        sys.path.remove(str(SCRIPTS))


# --- the resolution is not this machine's answer ------------------------------


EXPORT = """\
# This file was autogenerated by uv
accelerate==1.11.0
    # via warlock
colorama==0.4.6 ; sys_platform == 'win32'
    # via click
nvidia-cublas-cu12==12.8.4.1 ; platform_machine == 'x86_64' and sys_platform == 'linux'
    # via torch
triton==3.4.0 ; platform_machine == 'x86_64' and sys_platform == 'linux'
    # via torch
bpy==5.2.0 ; python_version >= '3.13' and python_version < '3.14'
torch==2.8.0+cu128
"""


def test_the_linux_cuda_stack_never_reaches_a_windows_pack(maker):
    """``uv export`` emits the whole resolution with its markers still on. A
    generator that read the lines at face value would collect Linux CUDA
    wheels and a Linux-only triton for a Windows installer."""
    selected = maker.parse_export(EXPORT)
    assert "nvidia-cublas-cu12" not in selected
    assert "triton" not in selected
    # And the markers that *are* true for the shipped runtime keep their lines.
    assert selected["colorama"] == "0.4.6"
    assert selected["bpy"] == "5.2.0"
    assert selected["torch"] == "2.8.0+cu128"


def test_an_unpinned_export_line_is_refused(maker):
    with pytest.raises(maker.PackError):
        maker.parse_export("httpx>=0.27\n")


def test_the_target_environment_is_the_runtime_the_installer_ships(maker):
    """Not the machine building the pack. The values are
    ``installer/runtime-manifest.json``'s pin restated in PEP 508's words, and
    a marker naming something absent from this dict raises rather than
    evaluating to nonsense."""
    manifest = maker.json.loads(
        (ROOT / "installer" / "runtime-manifest.json").read_text(encoding="utf-8")
    )
    assert manifest["python"]["major_minor"] == maker.TARGET_ENVIRONMENT["python_version"]
    assert maker.TARGET_ENVIRONMENT["sys_platform"] == "win32"
    assert maker.TARGET_ENVIRONMENT["platform_machine"] == "AMD64"


# --- choosing one wheel out of several ----------------------------------------


@pytest.mark.parametrize(
    "filename, wanted",
    [
        ("torch-2.8.0+cu128-cp313-cp313-win_amd64.whl", True),
        # The free-threaded build carries the same interpreter tag and only the
        # ABI tells them apart.
        ("torch-2.8.0+cu128-cp313-cp313t-win_amd64.whl", False),
        ("torch-2.8.0+cu128-cp313-cp313-manylinux_2_28_x86_64.whl", False),
        ("diffusers-0.31.0-py3-none-any.whl", True),
        # Stable-ABI wheels are tagged with the *oldest* interpreter they
        # support, and all three of these install into 3.13.
        ("safetensors-0.8.0-cp310-abi3-win_amd64.whl", True),
        ("tokenizers-0.22.2-cp39-abi3-win_amd64.whl", True),
        ("psutil-7.2.2-cp37-abi3-win_amd64.whl", True),
        # Newer than the target, so not ours however it is tagged.
        ("psutil-7.2.2-cp314-cp314t-win_amd64.whl", False),
        ("soxr-1.1.0-cp314-abi3-win_amd64.whl", False),
        ("thing-1.0-cp312-cp312-win_amd64.whl", False),
        ("not a wheel at all", False),
    ],
)
def test_a_wheel_is_ours_or_it_is_not(maker, filename, wanted):
    assert maker.is_target_wheel(filename) is wanted


def _entry(maker, *filenames: str):
    return maker.LockEntry(
        "thing",
        "1.0",
        tuple(maker.Source(f"https://example/{name}", "0" * 64) for name in filenames),
        None,
    )


def test_the_accelerated_wheel_wins_over_the_pure_python_fallback(maker):
    """Publishing both is normal -- ``charset-normalizer`` does -- and taking
    the fallback would quietly install the slow path."""
    chosen = maker.select_wheel(
        _entry(
            maker,
            "charset_normalizer-3.4.9-py3-none-any.whl",
            "charset_normalizer-3.4.9-cp313-cp313-win_amd64.whl",
        )
    )
    assert chosen.filename == "charset_normalizer-3.4.9-cp313-cp313-win_amd64.whl"


def test_two_equally_specific_wheels_are_a_refusal_not_a_coin_toss(maker):
    with pytest.raises(maker.PackError):
        maker.select_wheel(
            _entry(
                maker,
                "thing-1.0-cp313-cp313-win_amd64.whl",
                "thing-1.0-1-cp313-cp313-win_amd64.whl",
            )
        )


def test_a_distribution_with_no_windows_wheel_answers_none(maker):
    only_linux = _entry(maker, "mojimoji-0.0.13-cp313-cp313-manylinux1_x86_64.whl")
    assert maker.select_wheel(only_linux) is None


# --- who claims what -----------------------------------------------------------


def test_what_the_base_installer_already_ships_is_claimed_by_nobody(maker):
    base = {"httpx": "0.27", "numpy": "1.26"}
    per_pack = {
        "text2image": {"httpx": "0.27", "numpy": "1.26", "torch": "2.8.0"},
        "rig": {"httpx": "0.27", "bpy": "5.2.0"},
        "music": {"httpx": "0.27", "torch": "2.8.0", "librosa": "0.10"},
    }
    claimed = maker.claims(base, per_pack)
    assert "httpx" not in claimed and "numpy" not in claimed
    # Shared by both torch packs, and in registry order rather than call order.
    assert claimed["torch"] == ["text2image", "music"]
    assert claimed["bpy"] == ["rig"]
    assert claimed["librosa"] == ["music"]


def test_one_distribution_at_two_versions_is_refused(maker):
    """One pack directory cannot hold two builds of one distribution, and the
    installer would apply whichever it saw last."""
    with pytest.raises(maker.PackError):
        maker.claims(
            {},
            {
                "text2image": {"torch": "2.8.0"},
                "rig": {},
                "music": {"torch": "2.7.0"},
            },
        )


# --- against the real lock ------------------------------------------------------


@pytest.fixture(scope="module")
def real_lock(maker):
    return maker.load_lock(ROOT / "uv.lock")


def test_every_locked_wheel_url_carries_a_sha256(maker, real_lock):
    """The hash is what makes downloading by URL safe to do at all."""
    for entry in real_lock.values():
        for wheel in entry.wheels:
            assert len(wheel.sha256) == 64, f"{entry.name}: {wheel.url}"


def test_exactly_three_locked_distributions_have_no_windows_wheel(maker, real_lock):
    """``docopt``, ``mojimoji`` and ``unidic-lite``, and the number matters: a
    fourth means another distribution has to be *built* at pack time, which is
    a compiler requirement on the build host and a slower, less reproducible
    pack. It is a change someone should read rather than discover.

    This test is also the one that caught reading ``cpXY-abi3`` as an exact
    interpreter match -- four distributions were being sent down the
    build-from-source path that publish perfectly good stable-ABI wheels.
    """
    from importlib.metadata import distributions

    from packaging.utils import canonicalize_name

    # Scoped to what is actually installed here rather than to the whole lock:
    # this environment is a Windows sync of every extra, so its distributions
    # are precisely the set a pack has to be able to supply. The lock also
    # holds the Linux CUDA stack, which has no Windows wheel *and no business
    # in a Windows pack* -- counting those would make this test assert the
    # opposite of what it means.
    here = {canonicalize_name(dist.metadata["Name"]) for dist in distributions()}
    sdist_only = {
        name
        for name, entry in real_lock.items()
        if name in here and name != "warlock" and maker.select_wheel(entry) is None
    }
    assert sdist_only == {"docopt", "mojimoji", "unidic-lite"}


def test_every_sdist_only_distribution_has_an_sdist_to_build_from(maker, real_lock):
    for name in ("docopt", "mojimoji", "unidic-lite"):
        assert real_lock[name].sdist is not None


def test_the_torch_wheels_chosen_are_the_windows_cuda_ones(maker, real_lock):
    """The three ``SIZELESS_DISTS``, which are also the three whose wrong build
    would be least visible: a manylinux torch simply never imports."""
    for name in packs.SIZELESS_DISTS:
        chosen = maker.select_wheel(real_lock[name])
        assert chosen is not None
        assert chosen.filename.endswith("cp313-cp313-win_amd64.whl"), chosen.filename
        assert "+cu128" in chosen.filename


# --- the output the app has to be able to read ----------------------------------


def test_the_manifest_the_generator_writes_is_one_the_app_accepts(maker, tmp_path):
    """The generator's output and ``warlock.packs``' reader are the two halves
    of one contract, and finding out at install time that they disagree is
    finding out from the user."""
    collected = tmp_path / "torch-2.8.0-cp313-cp313-win_amd64.whl"
    collected.write_bytes(b"not really a wheel, but a real file with a real size")
    manifest = maker.build_manifest(
        lock={
            "torch": maker.LockEntry(
                "torch",
                "2.8.0",
                (maker.Source(f"file:///{collected.name}", maker._sha256(collected)),),
                None,
            )
        },
        claimed={"torch": ["text2image", "music"]},
        out_dir=tmp_path,
        unpacked={"torch": 9_000},
        offline=True,
    )
    parsed = packs.parse_manifest(manifest)
    assert packs.total_bytes(parsed.wheels) == collected.stat().st_size
    assert packs.installed_bytes(parsed.wheels) == 9_000
    # And the shared wheel is one download for the pair, not two.
    assert len(packs.plan(parsed, ["text2image", "music"])) == 1


def test_a_missing_file_is_refused_rather_than_written_as_a_zero(maker, tmp_path):
    with pytest.raises(maker.PackError):
        maker.build_manifest(
            lock={
                "torch": maker.LockEntry(
                    "torch",
                    "2.8.0",
                    (
                        maker.Source(
                            "https://example/torch-2.8.0-cp313-cp313-win_amd64.whl",
                            "0" * 64,
                        ),
                    ),
                    None,
                )
            },
            claimed={"torch": ["text2image"]},
            out_dir=tmp_path,
            unpacked={},
            offline=True,
        )


def test_a_claimed_distribution_the_lock_does_not_know_is_refused(maker, tmp_path):
    with pytest.raises(maker.PackError):
        maker.build_manifest(
            lock={}, claimed={"torch": ["music"]}, out_dir=tmp_path, unpacked={}, offline=True
        )
